apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app-client
  namespace: weather-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-app-client
  template:
    metadata:
      labels:
        app: weather-app-client
    spec:
      containers:
        - name: weather-app-client
          image: pietervardi/weather-app-client:1.0.1
          ports:
            - containerPort: 80