apiVersion: v1
kind: Service
metadata:
  name: weather-app-client-service
  namespace: weather-app
spec:
  selector:
    app: weather-app-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
