apiVersion: v1
kind: Service
metadata:
  name: weather-app-auth-service
  namespace: weather-app
spec:
  selector:
    app: weather-app-auth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
